In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

# Solution :-

import numpy as np 

null_vector = np.zeros(10) 
null_vector[4] = 1 
print('The Required answer is : ',null_vector)

The Required answer is :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# 2.Create a vector with values ranging from 10 to 49.
import numpy as np

vector = np.arange(10,50)
print('The required vector is : ',vector)

The required vector is :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

print('The 3x3 matrix is : ' ,matrix)

The 3x3 matrix is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np 

list_1 = [1,2,0,0,4,0] 

print("Non-zero elements indices:") 

result = np.nonzero(list_1) 

print('The result is : ' ,result)

Non-zero elements indices:
The result is :  (array([0, 1, 4], dtype=int64),)


In [6]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np 

array = np.random.randint(low=1, high=150, size=(10, 10)) 

print("The 10x10 array of random values is:\n") 
print(array) 

print("\nThe minimum value in the array is:", np.min(array)) 
print("The maximum value in the array is:", np.max(array))

The 10x10 array of random values is:

[[122 128 143 138  58 115  92 107  30  60]
 [ 20  70  36 131  23  40 104 143  21 123]
 [ 41 120  54  14   7 100  66  37  29 125]
 [ 63  12 128 105 141  54 139  81  72  50]
 [ 46  35  41 142  41   2  21 143   2  86]
 [ 31  67  59 128 144 114   7  50 148  67]
 [ 96 120  85  90  17   8 146  67 111 140]
 [ 54  37 129   6   8  56  11  93  50  29]
 [ 72 122 101  58  71  41 141  52  46 119]
 [126  75  83 144  14  66  88   7  35  91]]

The minimum value in the array is: 2
The maximum value in the array is: 148


In [7]:
# 6. Create a random vector of size 30 and find the mean value.


import numpy as np

rand_vector = np.random.randint(1,100,30)

mean_value = np.mean(rand_vector)

print("Random vector is :", rand_vector)
print("Mean value of the vector is :", mean_value)

Random vector is : [97 20  3 56 43 89 79 59 47 71 17 71 40 10 32 24 50 23 53 35 18 48 23 89
 25  1 51 88 10 36]
Mean value of the vector is : 43.6
